export const HAZARDS = {
  landslide: {
    id: 'landslide',
    label: 'Landslide',
    icon: 'mountain',
    accent: '#e7a96b',
    secondary: '#8c5d3b',
    glow: 'rgba(231,169,107,.18)',
    background: '#100d0a',
    description: 'Slope instability driven by rainfall, soil saturation and terrain.',
    parameters: ['Rainfall', 'Soil moisture', 'Slope', 'Ground movement'],
  },
  flood: {
    id: 'flood',
    label: 'Flood',
    icon: 'waves',
    accent: '#5bc7e8',
    secondary: '#256d91',
    glow: 'rgba(91,199,232,.18)',
    background: '#061016',
    description: 'Inundation risk driven by rainfall, river levels and drainage capacity.',
    parameters: ['Rainfall', 'River level', 'Soil moisture', 'Drainage load'],
  },
  cyclone: {
    id: 'cyclone',
    label: 'Cyclone',
    icon: 'wind',
    accent: '#a99aff',
    secondary: '#5e52ad',
    glow: 'rgba(169,154,255,.19)',
    background: '#0a0815',
    description: 'Severe tropical system risk driven by wind, pressure and ocean conditions.',
    parameters: ['Wind speed', 'Pressure', 'Sea temperature', 'Storm surge'],
  },
  earthquake: {
    id: 'earthquake',
    label: 'Earthquake',
    icon: 'activity',
    accent: '#ff8065',
    secondary: '#9b3d31',
    glow: 'rgba(255,128,101,.17)',
    background: '#120907',
    description: 'Seismic hazard assessed from historical activity and ground motion.',
    parameters: ['Magnitude', 'Ground motion', 'Depth', 'Fault proximity'],
  },
  wildfire: {
    id: 'wildfire',
    label: 'Wildfire',
    icon: 'flame',
    accent: '#ff6c4c',
    secondary: '#a93c2a',
    glow: 'rgba(255,108,76,.19)',
    background: '#120906',
    description: 'Fire spread potential driven by heat, dryness, wind and vegetation.',
    parameters: ['Temperature', 'Humidity', 'Wind', 'Fuel dryness'],
  },
  heatwave: {
    id: 'heatwave',
    label: 'Heatwave',
    icon: 'sun',
    accent: '#ffd166',
    secondary: '#a87822',
    glow: 'rgba(255,209,102,.17)',
    background: '#110e06',
    description: 'Extreme heat risk based on temperature, humidity and persistence.',
    parameters: ['Temperature', 'Feels like', 'Humidity', 'Heat index'],
  },
  drought: {
    id: 'drought',
    label: 'Drought',
    icon: 'droplets',
    accent: '#d6ad68',
    secondary: '#8b6733',
    glow: 'rgba(214,173,104,.15)',
    background: '#100d08',
    description: 'Water stress risk driven by rainfall deficit, soil and reservoir conditions.',
    parameters: ['Rain deficit', 'Soil moisture', 'Reservoir level', 'Dryness index'],
  },
}
